<div class="panel panel-default">
	<div class="panel-heading">Messages</div>
	<div class="panel-body panel-detail-projet">
		<div class="list-group">
		<?php

			foreach ($messages as $key => $message) {
				echo '<a class="list-group-item infoMessage" id="getContent' .  $message->getId() . '">
					<div class="row">
						<div class="col-md-6">' . $message->getUserIdUser()->getIdentite() . ' - ' . $message->getObjet() . '</div>
						<div class="col-md-6" style="text-align: right">' . $message->getDate() . '</div>
					</div>
				</a>';
				echo '<div id="content' . $message->getId() . '"></div>';
			}

		?>
		</div>
	</div>
</div>

<?php
	if (isset($script_foot)) {
		echo $script_foot;
	}
?>