<?php

	echo ' <br><div class="row">
		<div class="col-xs-3">
			<a href="#" class="thumbnail">
				<img src="' . '" alt="' . $projet->getNom() . '">
			</a>
		</div>
		<div class="col-xs-9">
			<div class="panel panel-default">
				<div class="panel-heading">' . $projet->getNom() . '</div>
					<div class="panel-body">
						<div class="col-md-12 text-justify">
							<strong>Nom :</strong><br>
							' . $projet->getNom() . '<br><br>
							<strong>Description :</strong><br>
							' . $projet->getDescription() . '<br><br>
						</div>
						<div class="col-md-6">
							<strong>Date de création :</strong><br>
							' . $projet->getDateLancement() . '
						</div>
						<div class="col-md-6">
							<strong>Date de mise à jour :</strong><br>
							' . $projet->getDateFinPrevue() . '
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="equipe">

		</div>
		<div class="input-group btnMessage">
				<button class="btn btn-default" id="btnMessage">Messages...</button>
		</div>
		<div id="messages"></div>
	</div>';

?>