<h3>Mes projets []</h3>
<?php
	foreach ($projets as $projet) {
		echo '<div class="form-inline">
			<div class="input-group nomProjet">
				<h5>' . $projet->getNom() . '</h5>
			</div>
			<div class="input-group barreAvancement">
				<div class="progress">
					<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
				        60%
					</div>
				</div>
			</div>
			<div class="input-group jourRestant">
				<h5>' . $projet->reste->format("%d jours restants") . '</h5>
			</div>
			<div class="input-group btnOuvrir">
				<a class="btn btn-default" >Ouvrir...</a>
			</div>
		</div>';
	}
?>